[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
optimism = "https://optimism.alchemyapi.io/v2/1234567"
eth_rpc_url = "https://example.com/"
blast_rpc_url = "https://rpc.blast.io"
sepoliaBlast_rpc_url = "https://sepolia.blast.io"
etherscan_api_key = "YOURETHERSCANAPIKEY"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
